services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/learnwith?schema=public
      - JWT_SECRET=replace_with_your_secure_jwt_secret_at_least_32_chars
      - FRONTEND_URL=http://localhost:3030
      - ALLOWED_ORIGINS=http://localhost:3030
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - GOOGLE_CALLBACK_URL=http://localhost:4000/api/auth/google/callback
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      # Mount for persistent logs if needed
      - ./logs:/usr/src/app/logs
      # Optional: Mount for development (comment out in production)
      # - .:/usr/src/app
      # - /usr/src/app/node_modules
    networks:
      - learnwith-network

  db:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=learnwith
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - learnwith-network

volumes:
  postgres_data:

networks:
  learnwith-network:
    driver: bridge 
