# .github/workflows/docker-publish.yml
name: Docker Build and Publish

on:
  push:
    branches:
      - main # Or your primary branch (e.g., master)
  # You can also trigger on pull requests, tags, etc.

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required for GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Option 1: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Option 2: Login to GitHub Container Registry (GHCR)
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            # For Docker Hub: your_dockerhub_username/your_app_name:latest
            # Example: mydockeruser/my-auth-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/your_app_name:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/your_app_name:${{ github.sha }}

            # For GHCR: ghcr.io/your_github_username/your_repository_name:latest
            # Example: ghcr.io/mygithubuser/my-auth-repo:latest
            # ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
            # ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
          # Optional: Add build arguments if your Dockerfile needs them
          # build-args: |
          #   ARG_NAME=value
